DROP DATABASE IF EXISTS cmpe226;
CREATE DATABASE cmpe226;
USE cmpe226;

CREATE TABLE IF NOT EXISTS user(
uid INT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(60) NOT NULL,
email VARCHAR(100) NOT NULL UNIQUE,
password CHAR(100) NOT NULL,
role VARCHAR(60) NOT NULL,
discount INT(60) DEFAULT 0
);

CREATE TABLE IF NOT EXISTS theater(
tid INT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
tname VARCHAR(60) NOT NULL UNIQUE,
address VARCHAR(60) NOT NULL,
state VARCHAR(60) NOT NULL,
city VARCHAR(60) NOT NULL,
phone int(60) NOT NULL,
admin_id int(60) NOT NULL REFERENCES user(uid)
);

ALTER TABLE theater ADD INDEX (city);

CREATE TABLE IF NOT EXISTS screen(
show_id INT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
tid INT(20) NOT NULL REFERENCES theater(tid),
scid INT(20) NOT NULL,
mid INT(20) NOT NULL,
show_date DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS screenSeats(
tid INT(20) NOT NULL REFERENCES theater(tid),
scid INT(20) NOT NULL REFERENCES screen(scid),
total_seats INT(20) NOT NULL,
PRIMARY KEY (tid, scid)
);

CREATE TABLE IF NOT EXISTS movie(
mid INT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
mname VARCHAR(60) NOT NULL,
genre VARCHAR(60) NOT NULL,
price FLOAT NOT NULL,
duration INT(10) NOT NULL
);

CREATE TABLE IF NOT EXISTS show_time(
show_id int(20) NOT NULL REFERENCES screen(show_id),
show_time TIME NOT NULL,
primary key(show_id, show_time)
);

CREATE TABLE IF NOT EXISTS seat(
seat_id INT(20) NOT NULL AUTO_INCREMENT,
status boolean default false,
show_time TIME,
show_id INT(20) REFERENCES screen(show_id),
uid INT(20) REFERENCES user(uid),
primary key(seat_id, show_id, uid)
);